name: Pruebas BDD y Unitarias

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Ejecutar pruebas unitarias
      run: |
        source venv/bin/activate
        pytest --cov=src tests/

    - name: Ejecutar pruebas BDD
      run: |
        source venv/bin/activate
        behave
